<a href="https://colab.research.google.com/github/hassaanhameed786/NLP/blob/main/natural_language_processing_01_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bag of words (NLP Basics)

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

treat each sentence as a separate document and we make a list of all words from all the four documents excluding the punctuation 

In [76]:
class Category:
  BOOKS =  "BOOKS"
  CLOTHING = "CLOTHING"
train_x = ["I love the book", "this is the great book", "the fit is great", "i love my shoes" ,  "i like to read books", "t-shirt are best to fit"]
train_y = [Category.BOOKS, Category.BOOKS, Category.CLOTHING, Category.CLOTHING , Category.BOOKS, Category.CLOTHING]

['book', 'fit', 'great', 'is', 'love', 'my', 'shoes', 'the', 'this']

 converting NLP text into numbers is called vectorization in ML

In [62]:
vectorizer = CountVectorizer() # object


 create vectors,Vectors convert text that can be used by the machine learning algorithm.*italicized text*

In [63]:
vectors = vectorizer.fit_transform(train_x) # Learn the vocabulary dictionary and return document-term matrix.


We take the first document heck the frequency of words from the  unique words.

In [ ]:
print(vectors[0])

In [ ]:
print(vectors[1])

In [ ]:
print(vectors.toarray())


In [67]:
train_x

['I love the book',
 'this is the great book',
 'the fit is great',
 'i love my shoes']

 ["I love the book", "this is the great book","the fit is great", "i love my shoes" ]

In [68]:
print(vectorizer.get_feature_names())
print(vectors.toarray())

['book', 'fit', 'great', 'is', 'love', 'my', 'shoes', 'the', 'this']
[[1 0 0 0 1 0 0 1 0]
 [1 0 1 1 0 0 0 1 1]
 [0 1 1 1 0 0 0 1 0]
 [0 0 0 0 1 1 1 0 0]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


# Classification of the data

In [69]:
from sklearn import svm

In [70]:
clf_svm =svm.SVC(kernel='linear')


In [77]:

vectorizer = CountVectorizer() # object 
train_x_vectors = vectorizer.fit_transform(train_x)


In [78]:
clf_svm.fit(train_x_vectors, train_y)

SVC(kernel='linear')

In [79]:
# test_x =vectorizer.transform(['sport shoes are good for walk'])

In [90]:
test_x =vectorizer.transform(['reading book is a good habbit'])

In [91]:
# test_x =vectorizer.transform(['the best book for nlp is '])

In [92]:
clf_svm.predict(test_x)

array(['BOOKS'], dtype='<U8')

In [93]:
test_x =vectorizer.transform(['reading books is a good habbit'])

in this case get not predict accurate because in our vec no words similar to books :

In [95]:
clf_svm.predict(test_x)

array(['CLOTHING'], dtype='<U8')